# ------------------------------------------------------------------------------
# Size Reduction
# ------------------------------------------------------------------------------

# Remove documentation and localization files that are typically unnecessary
# in containers and automated environments.

path-exclude=/usr/share/doc/*
path-exclude=/usr/share/man/*
path-exclude=/usr/share/groff/*
path-exclude=/usr/share/info/*
path-exclude=/usr/share/lintian/*
path-exclude=/usr/share/linda/*

# Preserve package licensing information.
path-include=/usr/share/doc/*/copyright

# Keep only English locales.
path-exclude=/usr/share/locale/*
path-include=/usr/share/locale/en*
