#!/usr/bin/env bash

# Function to display help.
show_help() {
  echo "Usage: $0 INSTANCE [options]"
  echo
  echo "INSTANCE                                    The VM instance's name (required)"
  echo "Options:"
  echo "  -p, --project NAME                        Set the project name (default: audiora)"
  echo "  -z, --zone ZONE                           Set the zone to use (default: us-east1-b)"
  echo "  -h, --help                                Display this help message"
}

# Check if at least one argument is provided.
if [[ "$#" -eq 0 ]]; then
  echo "Error: No arguments provided."
  show_help
  exit 1
fi

# The first argument is the required "instance".
INSTANCE_NAME="$1"
shift # Remove the first argument from the list.

# Default values.
PROJECT_NAME="audiora"
ZONE="us-east1-b"

# Parse command-line options.
while (( "$#" )); do
  case "$1" in
    -p|--project)
      PROJECT_NAME="$2"
      shift 2
      ;;
    -z|--zone)
      ZONE="$2"
      shift 2
      ;;
    -h|--help)
      show_help
      exit 0
      ;;
    --)
      shift
      break
      ;;
    -*) # unsupported flags
      echo "Error: Unsupported flag $1" >&2
      exit 1
      ;;
    *) # preserve positional arguments
      shift
      ;;
  esac
done

# Create a new VM instance with the startup script
gcloud compute instances reset "${INSTANCE_NAME}" \
    --project="${PROJECT_NAME}" \
    --zone="${ZONE}" \

echo "VM instance ${INSTANCE_NAME} reset."
