#!/usr/bin/env bash

shutdown_log_file=/var/log/shutdown.log

export DEBIAN_FRONTEND="noninteractive"

# Check if the user is root or running the script with sudo.
if [[ ${EUID} -ne 0 ]]; then
    echo "This script must be run as root or with sudo privileges."
    exit 1
fi

# Function to log output
log() {
  "$@" >> "${shutdown_log_file}" 2>&1
}

update_apt() {
  echo "Updating apt packages..."
  sudo DEBIAN_FRONTEND=noninteractive apt-get update --yes -o Dpkg::Use-Pty=0
}

upgrade_packages() {
  echo "Upgrading apt packages..."
  update_apt
  sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes -o Dpkg::Use-Pty=0
}

install_packages() {
  echo "Installing apt packages..."
  # List of packages to install
  local packages=("$@")

  # Wait for the lock to be released
  while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 || sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do
    echo "Waiting for dpkg lock to be released..."
    sleep 5
  done

  # Install packages
  update_apt
  sudo DEBIAN_FRONTEND=noninteractive apt-get install --yes -o Dpkg::Use-Pty=0 "${packages[@]}"
}

main() {
  local shutdown_time
  shutdown_time=$(date +%s)
  echo "VM shutdown at ${shutdown_time}."
}

log main
