#!/usr/bin/env bash

startup_log_file=/var/log/startup.log

export DEBIAN_FRONTEND="noninteractive"

# Check if the user is root or running the script with sudo.
if [[ ${EUID} -ne 0 ]]; then
    echo "This script must be run as root or with sudo privileges."
    exit 1
fi

# Function to log output
log() {
  "$@" >> "${startup_log_file}" 2>&1
}

disable_auto_updates() {
  echo "Temporarily disabling apt auto updates..."
  sudo systemctl stop apt-daily.timer
  sudo systemctl disable apt-daily.timer
  sudo systemctl stop apt-daily-upgrade.timer
  sudo systemctl disable apt-daily-upgrade.timer
}

enable_auto_updates() {
  echo "Re-enabling apt auto updates..."
  sudo systemctl enable apt-daily.timer
  sudo systemctl start apt-daily.timer
  sudo systemctl enable apt-daily-upgrade.timer
  sudo systemctl start apt-daily-upgrade.timer
}

update_apt() {
  echo "Updating apt packages..."
  sudo DEBIAN_FRONTEND=noninteractive apt-get update --yes -o Dpkg::Use-Pty=0
}

upgrade_packages() {
  echo "Upgrading apt packages..."
  update_apt
  sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes -o Dpkg::Use-Pty=0
}

install_packages() {
  echo "Installing apt packages..."
  # List of packages to install
  local packages=("$@")

  # Wait for the lock to be released
  while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 || sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do
    echo "Waiting for dpkg lock to be released..."
    sleep 5
  done

  # Install packages
  update_apt
  sudo DEBIAN_FRONTEND=noninteractive apt-get install --yes -o Dpkg::Use-Pty=0 "${packages[@]}"
}

import_gpg_key() {
  echo "Importing docker gpg key..."
  # Download the GPG key and save it to a temporary file
  if ! curl -fsSL https://download.docker.com/linux/debian/gpg -o /tmp/docker.gpg; then
    echo "Failed to download GPG key."
    exit 1
  fi

  # Import the GPG key
  if ! sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/docker.gpg /tmp/docker.gpg; then
    echo "Failed to import GPG key."
    exit 1
  fi

  sudo chmod a+r /etc/apt/keyrings/docker.gpg
}

add_docker_repository() {
  echo "Adding docker apt repository..."
  local arch
  local version_codename

  arch=$(dpkg --print-architecture)
  version_codename=$(. /etc/os-release && echo "${VERSION_CODENAME}")

  echo "deb [arch=${arch} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian ${version_codename} stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
}

install_docker() {
  echo "Installing docker..."
  # Install essential packages.
  install_packages "ca-certificates" "curl" "gnupg"

  # Add Docker's official GPG key.
  sudo install -m 0755 -d /etc/apt/keyrings

  import_gpg_key

  add_docker_repository

  install_packages "docker-ce" "docker-ce-cli" "containerd.io" "docker-buildx-plugin" "docker-compose-plugin"
}

check_docker() {
    echo "Upgrading apt packages..."
    if ! command -v docker &> /dev/null; then
      echo "Docker is not installed. Installing now..."

      # Install docker.
      install_docker

      # https://docs.docker.com/engine/install/linux-postinstall/
      # Enable and start Docker service.
      sudo systemctl enable docker.service
      sudo systemctl enable containerd.service
      sudo systemctl start docker.service
      sudo systemctl start containerd.service

      echo "Docker installed successfully."
  else
      echo "Docker is already installed."
  fi
}

main() {
  # Temporarily disable automatic apt updates.
  disable_auto_updates

  # Update package list and upgrade packages.
  upgrade_packages

  # Check if Docker is installed.
  check_docker

  # Re-enable automatic apt updates.
  enable_auto_updates
}

log main
