---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  git:
    taskfile: ".engineering/tasks/git.yml"
    description: Git-related tasks
    optional: true

  lint:
    taskfile: ".engineering/tasks/lint.yml"
    description: Linting tasks
    optional: true

  security:
    taskfile: ".engineering/tasks/security.yml"
    description: Security-related tasks
    optional: true
