#!/bin/sh

url="${1}"

if [ -z "${url}" ]; then
  echo "No arguments provided."
  # Handle the case where no argument is provided.
else
  echo "Downloading entire site: $url"
  # Handle the case where the first argument is a URL.

  wget \
    --no-config \
    --tries="10" \
    --progress="bar:force" \
    --continue \
    --show-progress \
    --mirror \
    --page-requisites \
    --convert-links \
    --no-parent \
    --adjust-extension \
    --random-wait \
    --retry-connrefused \
    --execute="robots = off" \
    --user-agent="$(fake-user-agent)" \
    "${url}"
fi
