#!/usr/bin/env bash
#
# Brief description of your script
# Copyright 2023 alan

function download_channel() {
    yt-dlp \
        --format 'bv*[height>=1080]+ba' \
        --embed-thumbnail \
        --embed-metadata \
        --embed-subs \
        --embed-chapters \
        --embed-info-json \
        --write-subs \
        --write-description \
        --write-playlist-metafiles \
        --write-link \
        --download-archive "$1.txt" \
        "https://www.youtube.com/$1/videos" -o '%(channel)s/%(title)s.%(ext)s'
}

function main() {
    download_channel "$1"
}

main "$@"

