# ------------------------------------------------------------------------------
# Global Defaults
# ------------------------------------------------------------------------------

# Enable colored output.
APT::Color "1";

# Run APT sandboxed as a specific user.
#
# Disabled:
# APT's default sandboxing behavior is generally preferred.
#
# APT::Sandbox::User "root";
