# ------------------------------------------------------------------------------
# Quiet Operation
# ------------------------------------------------------------------------------

# Useful in:
#
# - CI pipelines
# - Containers
# - Automated provisioning
#
# Disabled for workstation use because it hides useful information.

# APT::Get::Quiet "1";
# APT::Get::Quiet::Acquire "1";
# APT::Update::Quiet "1";
# APT::Update::Quiet::Acquire "1";
