# ------------------------------------------------------------------------------
# Repository Security
# ------------------------------------------------------------------------------

# Reject insecure repositories.
Acquire::AllowInsecureRepositories "0";

# Reject weak repositories.
Acquire::AllowWeakRepositories "0";

# Reject downgrades to insecure repositories.
Acquire::AllowDowngradeToInsecureRepositories "0";
