# ------------------------------------------------------------------------------
# HTTPS Configuration
# ------------------------------------------------------------------------------

# HTTPS timeout.
Acquire::https::Timeout "10";

# Verify TLS certificates.
Acquire::https::Verify-Peer "1";

# Verify hostnames.
Acquire::https::Verify-Host "1";

# Optional cache controls.
#
# Acquire::https::No-Cache "1";
# Acquire::https::No-Store "1";
