# ------------------------------------------------------------------------------
# Non-Interactive Operation
# ------------------------------------------------------------------------------

# Automatically preserve existing configuration files when possible.
force-confdef
force-confold

# Disable pager output.
no-pager

# Disable pseudo-terminal allocation.
Dpkg::Use-Pty "0";
