# ------------------------------------------------------------------------------
# Performance
# ------------------------------------------------------------------------------

# Enable only for ephemeral environments where filesystem durability is
# less important than installation speed.
#
# force-unsafe-io
