#!/bin/bash
# shellcheck disable=SC2034
# ------------------------------------------------------------------------------
# GRUB Defaults
# ------------------------------------------------------------------------------
#
# Apply changes:
#
#   sudo update-grub
#
# ------------------------------------------------------------------------------
GRUB_DEFAULT=0

GRUB_TIMEOUT_STYLE=hidden
GRUB_TIMEOUT=10

GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"

GRUB_CMDLINE_LINUX=""

# ------------------------------------------------------------------------------
# Theme
# ------------------------------------------------------------------------------
GRUB_THEME="/boot/grub/themes/bigsur/theme.txt"

# ------------------------------------------------------------------------------
# Colors
# ------------------------------------------------------------------------------
GRUB_COLOR_NORMAL="light-gray/black"
GRUB_COLOR_HIGHLIGHT="magenta/black"
