# ------------------------------------------------------------------------------
# Logging
# ------------------------------------------------------------------------------

# Write package installation and removal operations to the system dpkg log.
log /var/log/dpkg.log
