#
# Fish-native telemetry opt-outs. Disable this module by setting
# EGOHYGIENE_DISABLE_TELEMETRY=0 before runtime.fish is sourced.

if set -q EGOHYGIENE_FISH_PRIVACY_LOADED
    return 0
end
set -gx EGOHYGIENE_FISH_PRIVACY_LOADED true

if set -q EGOHYGIENE_DISABLE_TELEMETRY
    and test "$EGOHYGIENE_DISABLE_TELEMETRY" != "1"
    return 0
end

set -gx DO_NOT_TRACK 1
set -gx NO_ANALYTICS 1
set -gx NEXT_TELEMETRY_DISABLED 1
set -gx STORYBOOK_DISABLE_TELEMETRY 1
set -gx NUXT_TELEMETRY_DISABLED 1
set -gx GATSBY_TELEMETRY_DISABLED 1
set -gx YARN_ENABLE_TELEMETRY false
set -gx GOTELEMETRY off
set -gx DOTNET_CLI_TELEMETRY_OPTOUT 1
set -gx POWERSHELL_TELEMETRY_OPTOUT 1
set -gx CLOUDSDK_CORE_DISABLE_USAGE_REPORTING true
set -gx AZURE_CORE_COLLECT_TELEMETRY 0
set -gx SAM_CLI_TELEMETRY 0
set -gx HOMEBREW_NO_ANALYTICS 1
set -gx COCOAPODS_DISABLE_STATS true
set -gx CHECKPOINT_DISABLE 1
set -gx DAGSTER_DISABLE_TELEMETRY 1
set -gx HASURA_GRAPHQL_ENABLE_TELEMETRY false
set -gx PULUMI_DISABLE_TELEMETRY true
set -gx STRIPE_CLI_TELEMETRY_OPTOUT 1
set -gx NG_CLI_ANALYTICS false
set -gx ARDUINO_METRICS_ENABLED false
