#!/usr/bin/env python
import sys
from bcrypt import gensalt, hashpw

plain_text_password: str = str(sys.argv[1]).encode("utf-8")
hashed_password: str = hashpw(plain_text_password, gensalt())

print(hashed_password)

