#!/usr/bin/env python
import sys
from m3u8_To_MP4 import multithread_download
from pathlib import Path

url: str = str(sys.argv[1])
filename: str = str(sys.argv[2]) + ".mp4"

headers: dict = {}

print(f"Downloading from: {url}")
if len(sys.argv) > 2:
    referrer: str = str(sys.argv[3])
    headers["Referer"] = referrer
    multithread_download(url, headers)
else:
    multithread_download(url)

print(f"Renaming mp4 file to: {filename}")
out_file = Path.cwd().joinpath("m3u8_To_MP4.mp4").rename(filename)

print(f"Downloaded to: {out_file}")

