#!/usr/bin/env bash
#
# Convert image file to a png with an alpha channel.
# Copyright 2023 alan

# Function to print usage information
print_usage() {
    echo "Usage: $(basename "$0") <input_image>"
}

# Function to handle cleanup and exit
cleanup_and_exit() {
    local exit_code="$1"
    local error_message="$2"

    if [ -n "$error_message" ]; then
        echo "Error: ${error_message}"
    fi

    exit "${exit_code}"
}

# Function to perform the image conversion
convert_image() {
    local input_file="$1"
    local output_file="$2"

    convert "${input_file}" -alpha set -channel RGBA -background none -flatten "${output_file}"

    if [ $? -ne 0 ]; then
        cleanup_and_exit 2 "Failed to convert ${input_file} to ${output_file}."
    fi
}

# Trap function to catch errors and signals
trap 'cleanup_and_exit 1 "An unexpected error occurred."' ERR SIGHUP SIGINT SIGTERM

function main() {
    # Check if an argument is provided
    if [ "$#" -ne 1 ]; then
        echo "Usage: $(basename "$0") <input.jpg>"
        exit 1
    fi

    # Get the input file name
    input_file="$1"

    # Check if the input file exists
    if [ ! -f "$input_file" ]; then
        echo "File not found: $input_file"
        exit 1
    fi
    
    # Extract the filename without the extension
    filename=$(basename -- "$input_file")
    extension="${filename##*.}"
    filename_no_ext="${filename%.*}"
    
    # List of supported extensions
    supported_extensions=("jpg" "jpeg" "png" "bmp" "gif" "tiff")


    # Check if the input file has a supported extension
    if [[ ! " ${supported_extensions[@]} " =~ " ${extension,,} " ]]; then
        cleanup_and_exit 1 "The input file must have a supported extension. Supported extensions are: ${supported_extensions[*]}"
    fi
    
    # Initialize output file name and counter
    output_file="${filename_no_ext}.png"
    counter=1
    
    # Check if the output file already exists, and find an available name if it does
    while [ -f "$output_file" ]; do
        output_file="${filename_no_ext}_${counter}.png"
        ((counter++))
    done
    
    # Perform the conversion
    convert_image "$input_file" "$output_file"

    echo "Conversion successful. Output saved as $output_file"
}

main "$@"
