# cspell:ignore DBDIR LOGDIR dbout

# ------------------------------------------------------------------------------
# Directories
# ------------------------------------------------------------------------------
@@define DBDIR=/var/lib/aide
@@define LOGDIR=/var/log/aide

# ------------------------------------------------------------------------------
# Database
# ------------------------------------------------------------------------------
database=file:@@{DBDIR}/aide.db.gz
database_out=file:@@{DBDIR}/aide.db.new.gz

gzip_dbout=yes

# ------------------------------------------------------------------------------
# Reporting
# ------------------------------------------------------------------------------
report_url=stdout

# ------------------------------------------------------------------------------
# Includes
# ------------------------------------------------------------------------------
include=/etc/aide/aide.conf.d

# ------------------------------------------------------------------------------
# Rules
# ------------------------------------------------------------------------------
Checksums=sha512
