#!/usr/bin/env bash

# @file Operating System
# @brief Functions to detect Operating system and version.

# @description Identify the OS the function is run on.
#
# @noargs
#
# @example
#   os::detect_os
#   #Output
#   linux
#
# @exitcode 0  If OS is successfully detected.
# @exitcode 1 If unable to detect OS.
#
# @stdout Operating system name (linux, mac or windows).
os::detect_os() {
    declare uname os
    uname=$(command -v uname)

    case $("${uname}" | tr '[:upper:]' '[:lower:]') in
    linux*)
        os="linux"
        ;;
    darwin*)
        os="mac"
        ;;
    msys* | cygwin* | mingw* | nt | win*)
        # or possible 'bash on windows'
        os="windows"
        ;;
    *)
        return 1
        ;;
    esac
    printf "%s\n" "${os}"
}

# @description Identify the distribution flavour of linux.
#
# @noargs
#
# @example
#   os::detect_linux_distro
#   #Output
#   ubuntu
# @exitcode 0  If Linux distro is successfully detected.
# @exitcode 1 If unable to detect OS distro.
#
# @stdout Linux OS distribution name (ubuntu, debian, suse, etc.,).
os::detect_linux_distro() {
    declare distro
    if [[ -f /etc/os-release ]]; then
        # shellcheck disable=SC1091
        . "/etc/os-release"
        distro="${NAME}"
    elif type lsb_release >/dev/null 2>&1; then
        # linuxbase.org
        distro=$(lsb_release -si)
    elif [[ -f /etc/lsb-release ]]; then
        # For some versions of Debian/Ubuntu without lsb_release command
        # shellcheck disable=SC1091
        . /etc/lsb-release
        distro="${DISTRIB_ID}"
    elif [[ -f /etc/debian_version ]]; then
        # Older Debian/Ubuntu/etc.
        distro="debian"
    elif [[ -f /etc/SuSe-release ]]; then
        # Older SuSE/etc.
        distro="suse"
    elif [[ -f /etc/redhat-release ]]; then
        # Older Red Hat, CentOS, etc.
        distro="redhat"
    else
        return 1
    fi
    printf "%s\n" "${distro}" | tr '[:upper:]' '[:lower:]'
}

# @description Identify the Linux version.
#
# @noargs
#
# @example
#   os::detect_linux_version
#   #Output
#   20.04
#
# @exitcode 0  If Linux version is successfully detected.
# @exitcode 1 If unable to detect Linux version.
#
# @stdout Linux OS version number (18.04, 20.04, etc.,).
os::detect_linux_version() {
    declare distro_version
    if [[ -f /etc/os-release ]]; then
        # shellcheck disable=SC1091
        . "/etc/os-release"
        distro_version="${VERSION_ID}"
    elif type lsb_release >/dev/null 2>&1; then
        # linuxbase.org
        distro_version=$(lsb_release -sr)
    elif [[ -f /etc/lsb-release ]]; then
        # For some versions of Debian/Ubuntu without lsb_release command
        # shellcheck disable=SC1091
        . /etc/lsb-release
        distro_version="${DISTRIB_RELEASE}"
    else
        return 1
    fi
    printf "%s\n" "${distro_version}"
}

# @description Identify the MacOS version.
#
# @noargs
#
# @example
#   os::detect_linux_version
#   #Output
#   10.15.7
# @exitcode 0  If MacOS version is successfully detected.
# @exitcode 1 If unable to detect MacOS version.
#
# @stdout MacOS version number (10.15.6, etc.,)
os::detect_mac_version() {
    if [[ "$(os::detect_os)" = "mac" ]]; then
        declare mac_version
        mac_version="$(sw_vers -productVersion)"
        printf "%s\n" "${mac_version}"
    else
        return 1
    fi
}


# @description Check if an user exists in the system.
#
# @noargs
#
# @example
#   os::detect_linux_distro
#   #Output
#   ubuntu
# @exitcode 0  If Linux distro is successfully detected.
# @exitcode 1 If unable to detect OS distro.
#
# @stdout Linux OS distribution name (ubuntu, debian, suse, etc.,).
os::user_exists() {
    local user="${1:?user is missing}"
    id "$user" >/dev/null 2>&1
}

os::group_exists() {
    local group="${1:?group is missing}"
    getent group "$group" >/dev/null 2>&1
}

os::ensure_group_exists() {
    local group="${1:?group is missing}"

    if ! os::group_exists "$group"; then
        groupadd "$group" >/dev/null 2>&1
    fi
}

os::ensure_user_exists() {
    local user="${1:?user is missing}"
    local group="${2:-}"

    if ! os::user_exists "$user"; then
	useradd "$user" >/dev/null 2>&1
        if [[ -n "$group" ]]; then
            os::ensure_group_exists "$group"
            usermod -a -G "$group" "$user" >/dev/null 2>&1
        fi
    fi
}

os::delete_directory_contents() {
  find "${1}" -xdev -depth -mindepth 1 -exec rm -Rf {} \;
}


# Clear thumbnail directory.
os::clear_thumbnails() {
  os::delete_directory_contents "${HOME}/.cache/thumbnails"
}


# Clear clipboard.
os::clear_clipboard() {
  xsel --clipboard --clear
}


# Clear bash history.
os::clear_history() {
  history -c
}

# Empty trash.
os::empty_trash() {
  os::delete_directory_contents "$HOME/.local/share/Trash"
}

# Clear recent files.
os::clear_recent_files() {
  rm "$HOME/.local/share/recently-used.xbel"
}

# Disconnect NordVPN.
os::disconnect_vpn() {
  nordvpn disconnect > /dev/null
}

# Clear cache directories.
os::clear_cache_directories() {
  os::delete_directory_contents "$HOME/snap/brave/common/.cache"
}

# System cleaner.
os::clean() {
  os::clear_thumbnails
  os::clear_history
  os::clear_clipboard
  os::empty_trash
  os::clear_recent_files
  os::disconnect_vpn
}

os::get_total_memory() {
    echo $(($(grep MemTotal /proc/meminfo | awk '{print $2}') / 1024))
}


