---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: 👥 Contributors

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: write

jobs:
  contributors:
    name: 👥 Update Contributors
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout
        uses: actions/checkout@v4

      - name: 👥 Update Contributors
        uses: ./.github/actions/contributors

      - name: 💾 Commit Changes
        run: |
          git config user.name "github-actions[bot]"

          git config user.email \
            "41898282+github-actions[bot]@users.noreply.github.com"

          git add \
            .allcontributorsrc \
            CONTRIBUTORS.md

          if git diff --cached --quiet; then
            printf "No contributor changes detected.\n"
            exit 0
          fi

          git commit \
            --message "👥 update contributors"

          git push
